import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="bg-slate-400 text-white p-4 text-center">
        Welcome To Nextjs 15 Crash Course
      </header>
        {children}
        <footer className="bg-slate-400 text-white p-4 text-center">
          Tutorial by Sarah Hanks
        </footer>
      </body>
    </html>
  );
}
