import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nextjs Course",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <header className="bg-slate-400 text-white p-4 text-center">
        Welcome To Nextjs 15 Crash Course
      </header> */}
          <Navigation />
          {children}
          <footer className="bg-slate-400 text-white p-4 text-center">
            Tutorial by Sarah Hanks
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
